#!/usr/bin/env python3
"""Regenerate 01_Infrastructure/Infrastructure-State-Snapshot.md from live Proxmox state.

Read-only: only issues GET requests against the Proxmox API. Credentials are
read from the local, gitignored .vscode/mcp.json (never committed).

Usage:
    python3 09_Scripts/refresh_infra_snapshot.py
"""
import json
import ssl
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MCP_CONFIG = REPO_ROOT / ".vscode" / "mcp.json"
OUTPUT_FILE = REPO_ROOT / "01_Infrastructure" / "Infrastructure-State-Snapshot.md"


def load_credentials():
    cfg = json.loads(MCP_CONFIG.read_text())["mcpServers"]["proxmox-lab-mcp"]["env"]
    return cfg


def parse_kv(raw):
    if not raw:
        return {}
    return dict(part.split("=", 1) for part in str(raw).split(",") if "=" in part)


def bridges_from_config(config):
    bridges = set()
    for key, val in config.items():
        if key.startswith("net") and key[3:].isdigit():
            parsed = parse_kv(val)
            if "bridge" in parsed:
                bridges.add(parsed["bridge"])
    return ", ".join(sorted(bridges)) if bridges else "—"


def build_snapshot():
    cfg = load_credentials()
    base = cfg["PROXMOX_HOST"].rstrip("/") + "/api2/json"
    headers = {"Authorization": f"PVEAPIToken={cfg['PROXMOX_TOKEN_ID']}={cfg['PROXMOX_TOKEN_SECRET']}"}
    insecure = cfg.get("PROXMOX_INSECURE_TLS", "").lower() == "true"
    ctx = ssl._create_unverified_context() if insecure else ssl.create_default_context()

    def get(path):
        req = urllib.request.Request(base + path, headers=headers)
        with urllib.request.urlopen(req, context=ctx, timeout=20) as r:
            return json.load(r).get("data")

    lines = [
        "# 📡 Infrastructure State Snapshot (Auto-Generated)",
        "",
        "> ⚠️ **DO NOT HAND-EDIT THIS FILE.** Regenerated by "
        "`09_Scripts/refresh_infra_snapshot.py` from the live Proxmox API. "
        "To change infrastructure, modify Proxmox, then re-run the script.",
        "",
        f"**Last Verified:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Source:** `{cfg['PROXMOX_HOST']}` (read-only API token)",
        "",
    ]

    for node in get("/nodes") or []:
        node_name = node["node"]
        lines.append(f"## Node: `{node_name}`")
        lines.append(f"- Status: {node.get('status', 'unknown')}")
        lines.append(f"- CPUs: {node.get('maxcpu', '?')}")
        maxmem = node.get("maxmem")
        if maxmem:
            lines.append(f"- Memory: {round(int(maxmem) / (1024 ** 3), 1)} GiB")
        lines.append("")

        try:
            netcfg = get(f"/nodes/{node_name}/network") or []
        except urllib.error.HTTPError:
            netcfg = []
        bridges = [n for n in netcfg if n.get("type") == "bridge"]
        if bridges:
            lines.append("### Network Bridges")
            lines.append("| Bridge | Address | Active | Ports | Comment |")
            lines.append("|:---|:---|:---|:---|:---|")
            for b in sorted(bridges, key=lambda x: x.get("iface", "")):
                lines.append(
                    f"| `{b.get('iface')}` | {b.get('cidr', b.get('address', '—'))} "
                    f"| {'yes' if b.get('active') else 'no'} "
                    f"| {b.get('bridge_ports') or '—'} | {b.get('comments', '') or '—'} |"
                )
            lines.append("")

        vms = get(f"/nodes/{node_name}/qemu") or []
        lxcs = get(f"/nodes/{node_name}/lxc") or []
        if vms or lxcs:
            lines.append("### VMs & Containers")
            lines.append("| VMID | Type | Name | Status | Bridge(s) |")
            lines.append("|:---|:---|:---|:---|:---|")
            for v in sorted(vms, key=lambda x: x["vmid"]):
                config = get(f"/nodes/{node_name}/qemu/{v['vmid']}/config") or {}
                lines.append(
                    f"| {v['vmid']} | VM | {v.get('name', '—')} | {v.get('status', '—')} "
                    f"| {bridges_from_config(config)} |"
                )
            for c in sorted(lxcs, key=lambda x: x["vmid"]):
                config = get(f"/nodes/{node_name}/lxc/{c['vmid']}/config") or {}
                lines.append(
                    f"| {c['vmid']} | LXC | {c.get('name', '—')} | {c.get('status', '—')} "
                    f"| {bridges_from_config(config)} |"
                )
            lines.append("")

    return "\n".join(lines) + "\n"


def main():
    OUTPUT_FILE.write_text(build_snapshot())
    print(f"Wrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
